// JavaScript Document

var InterfaceMaster = (function () {
    var instance;

    function createInstance() {

        var object = new interfaceObject();

		function interfaceObject(){

			var self = this;
			var data;
			var gm = GameMaster.getInstance();
			var limitedPokemon = [];
			var context = "rankings"; // Used for internal reference
			var battle = new Battle();
			var numberAskedQuestions = 0;
			var numberCorrectAnswers = 0;
			var pokemon;
			var rankings;
			var chargedMove;
			var fastMove;
			var useOnlyReccomendedMoveset = true;
			var numberTopPokemons;

			this.questionAnswers = {}

			// Show useRecc toggle if previously set
			if(window.localStorage.getItem("useOnlyReccomendedMoveset") == "false"){
				$(".check.quiz-reccomended-moveset").removeClass("on");
				useOnlyReccomendedMoveset = false;
			}

			// The scenario generated by the rankings,
			// This really should be embedded in the ranking data but this is a quick fix for now
			var scenario = {
				slug: "custom",
				shields: [1,1],
				energy: [0,0]
			};

			var scenarios = [];

			this.context = "rankings"; // Used for external reference

			this.init = function(){
				scenarios = GameMaster.getInstance().data.rankingScenarios;

				if(! get){
					this.displayRankings("overall","1500","all");
				} else{
					this.loadGetData();
				}

				$(".format-select").on("change", selectFormat);
				$(".top-ranking-select").on("change", selectTopRankings);
				$(".league-select").on("change", selectLeague);
				$(".category-select").on("change", selectCategory);
				$("body").on("click", ".quiz-check-btn", checkAnswer);
				$("body").on("click", ".quiz-next-btn", nextQuestion);
				$("body").on("click", ".check", checkBox);
				$("body").on("click", ".check.quiz-reccomended-moveset", toggleUseOnlyReccomendedMoveset);

				pokeSearch.setBattle(battle);

				window.addEventListener('popstate', function(e) {
					get = e.state;
					self.loadGetData();
				});
			};

			// Initialize with starting value when page loads
			$(document).ready(function() {
				selectTopRankings();
			});

			function selectTopRankings(e){
				var selectNumberTopPokemons = $(".top-ranking-select option:selected").val();
				numberTopPokemons = selectNumberTopPokemons
			}

			// Toggle use only reccomended moveset

			function toggleUseOnlyReccomendedMoveset(e){
				useOnlyReccomendedMoveset = !useOnlyReccomendedMoveset
				window.localStorage.setItem("useOnlyReccomendedMoveset", useOnlyReccomendedMoveset)
			}

			// Grabs ranking data from the Game Master

			this.displayRankings = function(category, league, cup){

				var gm = GameMaster.getInstance();

				$(".quiz-container").html('');
				$(".loading").show();

				var format = gm.getFormat(cup, league);

				if(format && format.rules){
					$("a.format-rules").show();
				} else{
					$("a.format-rules").hide();
				}

				// Force 1500 if not general

				if((cup == "premier")&&(league == 1500)){
					league = 10000;

					$(".league-select option[value=\"10000\"]").prop("selected","selected");
				}

				if((cup == "classic")&&(league != 10000)){
					league = 10000;

					$(".league-select option[value=\"10000\"]").prop("selected","selected");
				}

				if(cup == "little"){
					league = 500;

					$(".league-select option[value=\"500\"]").prop("selected","selected");
				}

				if(cup == "littlejungle"){
					$(".little-jungle").show();
				} else{
					$(".little-jungle").hide();
				}

				battle.setCup(cup);
				battle.setCP(league);

				if(! battle.getCup().levelCap){
					battle.setLevelCap(50);
				}

				if(battle.getCup().link){
					$(".description.link").show();
					$(".description.link a").attr("href", battle.getCup().link);
					$(".description.link a").html(battle.getCup().link);
				} else{
					$(".description.link").hide();
				}

				// Check ranking details settings to show ranking details in one page or tabs

				if(settings.rankingDetails == "tabs"){
					$(".quiz-container").addClass("detail-tabs-on");
				}

				/* This timeout allows the interface to display the loading message before
				being thrown into the data loading loop */

				setTimeout(function(){
					gm.loadRankingData(self, category, league, cup);
				}, 50);

			}

			// Displays the grabbed data. Showoff.

			this.displayRankingData = function(rankings){

				var gm = GameMaster.getInstance();

				trials = 0;
				$(".quiz-feedback").text("")
				data = rankings;
				this.rankings = rankings;

				// Load meta group
				if(context != "custom"){
					var metaKey = $(".format-select option:selected").attr("meta-group");

					if(! gm.groups[metaKey]){
						runningResults = true;
						gm.loadGroupData(self, metaKey, data);
						return false;
					} else{
						metaGroupData = gm.groups[metaKey];
					}
				}

				// Sort rankings by selected sort method
				var sort = $(".category-select option:selected").attr("sort");

				switch(sort){
					case "score":
						data.sort((a,b) => (a.score > b.score) ? -1 : ((b.score > a.score) ? 1 : 0));
						$(".league-select-container > .ranking-header.right").html("Score");
						break;

					case "statproduct":
						data.sort((a,b) => (a.stats.product > b.stats.product) ? -1 : ((b.stats.product > a.stats.product) ? 1 : 0));
						$(".league-select-container > .ranking-header.right").html("Stat Product");
						break;

					case "attack":
						data.sort((a,b) => (a.stats.atk > b.stats.atk) ? -1 : ((b.stats.atk > a.stats.atk) ? 1 : 0));
						$(".league-select-container > .ranking-header.right").html("Attack");
						break;

					case "defense":
						data.sort((a,b) => (a.stats.def > b.stats.def) ? -1 : ((b.stats.def > a.stats.def) ? 1 : 0));
						$(".league-select-container > .ranking-header.right").html("Defense");
						break;

					case "stamina":
						data.sort((a,b) => (a.stats.hp > b.stats.hp) ? -1 : ((b.stats.hp > a.stats.hp) ? 1 : 0));
						$(".league-select-container > .ranking-header.right").html("Stamina");
						break;
				}

				// Pass this along to the custom ranking interface to fill in movesets
				if(context == "custom"){
					customRankingInterface.importMovesetsFromRankings(data);
				}

				// Show any restrictions
				var cup = battle.getCup().name;
				$(".limited").hide();
				limitedPokemon = [];

				if((gm.getCupById(cup))&&(gm.getCupById(cup).restrictedPokemon)){
					$(".limited").show();
					$(".check.limited").addClass("on");

					limitedPokemon = gm.getCupById(cup).restrictedPokemon;
				}

				if(battle.getCup().slots){
					$(".continentals").show();
				} else{
					$(".continentals").hide();
				}

				$(".section.white .opponents .quiz-container").html('');
				$(".section.white .yours .quiz-container").html('');

				// Initialize csv data

				csv = 'Pokemon,Score,Dex,Type 1,Type 2,Attack,Defense,Stamina,Stat Product,Level,CP,Fast Move,Charged Move 1,Charged Move 2,Charged Move 1 Count,Charged Move 2 Count,Buddy Distance,Charged Move Cost\n';


				// Create an element for each ranked Pokemon

				metaGroup = [];


				$(".loading").hide();

				var i = 0;
				var rankingDisplayIncrement = 15;

				if(settings.performanceMode){
					rankingDisplayIncrement = 5;
				}

				
				if(numberTopPokemons == 'ALL'){
					realNumberTopPokemons = rankings.length
				} else {
					realNumberTopPokemons = numberTopPokemons;
				}

				// Random index for "yours"
				this.quizRankingIndexYours = Math.floor(Math.random() * realNumberTopPokemons);

				// Random index for "opponents", different from "yours"
				do {
				this.quizRankingIndexOpponents = Math.floor(Math.random() * realNumberTopPokemons);
				} while (this.quizRankingIndexOpponents === this.quizRankingIndexYours);
				
				// Create your pokemon
				var yourPokemon = new Pokemon(rankings[this.quizRankingIndexYours].speciesId, 0, battle);
				yourPokemon.initialize(true);

				// Pick the fast moves
				if(useOnlyReccomendedMoveset){
					yourPokemon.selectMove("fast", rankings[this.quizRankingIndexYours].moveset[0])
				} else {
					// Pick among all available moves
					fastMoveIndex = Math.floor(Math.random() * yourPokemon.fastMovePool.length)
					yourPokemon.selectMove("fast", yourPokemon.fastMovePool[fastMoveIndex].moveId)
				}
				
				// Create opponent's pokemon
				var opponentsPokemon = new Pokemon(rankings[this.quizRankingIndexOpponents].speciesId, 0, battle);
				opponentsPokemon.initialize(true);
				
				// Pick the fast moves
				if(useOnlyReccomendedMoveset){
					opponentsPokemon.selectMove("fast", rankings[this.quizRankingIndexOpponents].moveset[0])
				} else {
					// Pick among all available moves
					fastMoveIndex = Math.floor(Math.random() * opponentsPokemon.fastMovePool.length)
					opponentsPokemon.selectMove("fast", opponentsPokemon.fastMovePool[fastMoveIndex].moveId)
				}

				try {
					self.displayRankingEntry(yourPokemon, true);
				} catch (err) {
					console.error(yourPokemon.speciesId + " could not be displayed", err);
				}
				try {
					self.displayRankingEntry(opponentsPokemon, false);
				} catch (err) {
					console.error(opponentsPokemon.speciesId + " could not be displayed", err);
				}
				fastMoveTiming(yourPokemon, opponentsPokemon)

				// Poi chiama la funzione finale
				self.completeRankingDisplay();
				numberAskedQuestions++
			}

			this.displayRankingEntry = function(pokemon, isYours){
				if(! pokemon.speciesId){
					return;
				}
				
				// Show the pokemon details
				var $el = $("<div class=\"rank typed-ranking quiz " + pokemon.types[0] + "\" type-1=\""+pokemon.types[0]+"\" type-2=\""+pokemon.types[1]+"\" data=\""+pokemon.speciesId+"\">" +
					"<div class=\"pokemon-info\">" +
						"<div class=\"name-container\">" +
							"<span class=\"name\">"+pokemon.speciesName+"</span>" +
							"<div class=\"quiz-moves-container\">" +
								"<div class=\"quiz-move\"><b>Fast Move:</b> "+ pokemon.fastMove.name + "</div>" +
							"</div>" +
						"</div>" +
						"<div class=\"type-container\"></div>" +
					"</div>" +
				"</div>");

				for(var i = 0; i < pokemon.types.length; i++){
					var typeStr = pokemon.types[i].charAt(0).toUpperCase() + pokemon.types[i].slice(1);
					if(pokemon.types[i] != "none"){
						$el.find(".type-container").append("<div class=\"type-info "+pokemon.types[i]+"\">"+typeStr+"</div>");
					}
				}

				if(isYours){
					$(".section.white .yours .quiz-container").append($el);
				} else {
					$(".section.white .opponents .quiz-container").append($el);
				}

				addHintMoveDetails(pokemon, isYours)
			}

			function fastMoveTiming(yourPokemon, opponentsPokemon) {
				$(".battle-results").hide();
				$(".optimal-timing-section .timeline").html("");

				var pokemon = [yourPokemon, opponentsPokemon]
				$(".quiz-feedback-explanation .name-attacker").html(pokemon[0].speciesName);
				$(".quiz-feedback-explanation .name-defender").html(pokemon[1].speciesName);

				var targetCooldown = 500;
				var startCooldown = pokemon[0].startCooldown - 500;

				// Optimal timing is N/A when the opponent has a shorter move that is divisible into your move, or both Pokemon have the same move
				if(pokemon[0].fastMove.cooldown % pokemon[1].fastMove.cooldown == 0){
					if(pokemon[0].startCooldown == pokemon[1].startCooldown){
						targetCooldown = 0;
					} else if(pokemon[0].startCooldown > pokemon[1].startCooldown){
						targetCooldown = 0;
					} else{
						targetCooldown = 500;
					}
				}

				// Pokemon with 2 turn moves can only throw on turn 2 of a 4 turn move
				if(pokemon[0].fastMove.cooldown == 1000 && pokemon[1].fastMove.cooldown == 2000){
					if(pokemon[0].startCooldown == pokemon[1].startCooldown){
						targetCooldown = 1000;
					} else {
						var cooldownDifference = (pokemon[0].startCooldown - pokemon[1].startCooldown) - 500;
						targetCooldown = 1000 - cooldownDifference;
					}
				}

				var displayCycles = 0;

				var optimalTimes = []; // Array that stores integer counts of Fast Moves that provide optimal timing
				var opponentFastCount = 0;
				var opponentOffset = 0;

				if(pokemon[0].startCooldown == pokemon[1].startCooldown){
					opponentOffset = 0;
				} else if(pokemon[0].startCooldown == 1000){
					opponentOffset = -500;
				} else if(pokemon[1].startCooldown == 1000){
					opponentOffset = 500;
				}

				for(var i = 1; displayCycles < 3; i++){
					var targetTurn = opponentOffset + (pokemon[1].fastMove.cooldown * i) - targetCooldown; // Target the last turn of the move

					if(targetCooldown > 0 && targetTurn > 0 && targetTurn % pokemon[0].fastMove.cooldown == 0){ // If this turn is divisible by your Fast Move duration
						optimalTimes.push(targetTurn / pokemon[0].fastMove.cooldown); // Number of moves you need to use to reach this optimal turn
						displayCycles++;
					} else if(targetCooldown == 0){
						displayCycles++;
					}

					opponentFastCount = i;
				}

				if(targetCooldown == 0){
					opponentFastCount = (displayCycles * pokemon[0].fastMove.cooldown) / pokemon[1].fastMove.cooldown;
				}


				// Display fast moves on timeline
				if(optimalTimes.length > 0){
					displayCycles = optimalTimes[2];
				}
				this.optimalTimes = optimalTimes;

				// Add an empty chunk at the beginning for 1 turn switch
				if(pokemon[0].startCooldown == 1000){
					$fastItem = $('<div class="item fast fade"><div class="chunk"></div></div>');
					$fastItem.css("flex", 1);
					$(".optimal-timing-section .timeline").eq(0).append($fastItem);
				}

				if(pokemon[1].startCooldown == 1000){
					$fastItem = $('<div class="item fast fade"><div class="chunk"></div></div>');
					$fastItem.css("flex", 1);
					$(".optimal-timing-section .timeline").eq(1).append($fastItem);
				}

				for(i = 0; i < displayCycles; i++){
					var $fastItem = $('<div class="item fast '+pokemon[0].fastMove.type+'"></div>');
					$fastItem.css("flex", pokemon[0].fastMove.turns + "");

					for(var n = 0; n < pokemon[0].fastMove.turns; n++){
						$fastItem.append('<div class="chunk"></div>')
					}

					if(optimalTimes.indexOf(i) == -1){
						$fastItem.addClass("fade");
					} else{
						$fastItem.addClass("throw");
					}

					$(".optimal-timing-section .timeline").eq(0).append($fastItem);
				}

				// Add an empty chunk at the end for a Charged Move space
				$(".quiz-feedback-explanation p").hide();

				if(targetCooldown > 0){
					$fastItem = $('<div class="item fast throw '+pokemon[0].fastMove.type+'"></div>');
					$fastItem.css("flex", targetCooldown / 500 + "");
					for(var i = 0; i < targetCooldown / 500; i++){
						$fastItem.append("<div class=\"chunk\"></div>");
					}
					$(".optimal-timing-section .timeline").eq(0).append($fastItem);

					$(".quiz-feedback-explanation .optimal-1").html(optimalTimes[0]);
					$(".quiz-feedback-explanation .optimal-2").html(optimalTimes[1]);
					$(".quiz-feedback-explanation .optimal-3").html(optimalTimes[2]);

					$(".quiz-feedback-explanation p.timing-most-optimal").show();
				} else if(pokemon[0].startCooldown == 1000 && pokemon[1].startCooldown == 0 && pokemon[0].fastMove.cooldown == pokemon[1].fastMove.cooldown
				&& pokemon[0].fastMove.cooldown != 500){
					$(".quiz-feedback-explanation p.timing-offset").show();
				} else{
					$(".quiz-feedback-explanation p.timing-none").show();
				}

				for(i = 0; i < opponentFastCount; i++){
					$fastItem = $('<div class="item fast '+pokemon[1].fastMove.type+'"></div>');
					$fastItem.css("flex", pokemon[1].fastMove.turns + "");
					for(var n = 0; n < pokemon[1].fastMove.turns; n++){
						$fastItem.append('<div class="chunk"></div>')
					}

					$(".optimal-timing-section .timeline").eq(1).append($fastItem);
				}

				// Add an empty chunk at the end  for 1 turn switch
				if($(".optimal-timing-section .timeline").eq(0).find(".chunk").length < $(".optimal-timing-section .timeline").eq(1).find(".chunk").length){
					$fastItem = $('<div class="item fast fade"><div class="chunk"></div></div>');
					$fastItem.css("flex", 1);
					$(".optimal-timing-section .timeline").eq(0).append($fastItem);
				} else if($(".optimal-timing-section .timeline").eq(1).find(".chunk").length < $(".optimal-timing-section .timeline").eq(0).find(".chunk").length){
					$fastItem = $('<div class="item fast fade"><div class="chunk"></div></div>');
					$fastItem.css("flex", 1);
					$(".optimal-timing-section .timeline").eq(1).append($fastItem);
				}

				//Show the section
				$(".battle-results").show();
			}

			this.completeRankingDisplay = function(){
				//when the data is loaded, show the question
				$(".quiz-question").show();
				$(".quiz-check-btn ").show();
				$(".quiz-next-btn ").show();
			}

			// Given JSON of get parameters, load these settings

			this.loadGetData = function(){

				if(! get){
					return false;
				}

				// Cycle through parameters and set them

				for(var key in get){
					if(get.hasOwnProperty(key)){

						var val = get[key];

						// Process each type of parameter

						switch(key){

							// Don't process default values so data doesn't needlessly reload

							case "cp":
								battle.setCP(val);
								break;

							case "cat":
								// Select by sort first if it exists
								if($(".category-select option[sort=\""+val+"\"]").length > 0){
									$(".category-select option[sort=\""+val+"\"]").first().prop("selected", "selected");
								} else{
									$(".category-select option[value=\""+val+"\"]").first().prop("selected", "selected");
								}

								// Show relevant description

								var category = $(".category-select option:selected").val();
								var sort = $(".category-select option:selected").attr("sort");

								$(".description").hide();
								if(sort == "score"){
									$(".description."+category).show();
								} else{
									$(".description."+sort).show();
								}
								break;

							case "cup":
								battle.setCup(val);
								break;

							case "p":
								// We have to wait for the data to load before we can jump to a Pokemon, so store this for later
								jumpToPoke = val;
								break;

						}
					}
				}

				// Load data via existing change function

				var cp = battle.getCP();
				var category = $(".category-select option:selected").val();
				var cup = battle.getCup().name;

				$(".format-select option[value=\""+cp+"\"][cup=\""+cup+"\"]").prop("selected","selected");

				self.displayRankings(category, cp, cup, null);
			}

			// When the view state changes, push to browser history so it can be navigated forward or back

			this.pushHistoryState = function(cup, cp, category, speciesId){
				if(context == "custom"){
					return false;
				}

				if(cup == "little"){
					cp = 500;
				}

				// Use the sort method for the non-score based categories
				var sort = $(".category-select option:selected").attr("sort");

				if(sort != "score"){
					category = sort;
				}

				var rankStr = "rankings/"+cup+"/"+cp+"/"+category+"/"

				if(speciesId){
					rankStr += speciesId+"/";
				}

				var url = webRoot+rankStr;

				var data = {cup: cup, cp: cp, cat: category, p: speciesId };

				window.history.pushState(data, "Rankings", url);

				// Send Google Analytics pageview
				gtag('event', 'Lookup', {
				  'category': 'Rankings',
				  'speciesId' : speciesId
				});

				gtag('event', 'page_view', {
				  page_title: speciesId + ' ' + document.title,
				  page_location: (host+rankStr),
				  pageview_type: 'virtual'
				});

				// Set document title
				let selectedFormat = gm.getFormat(cup, cp);

				if(selectedFormat){
					document.title = selectedFormat.title + " Rankings | PvPoke";
				} else{
					document.title = "Rankings | PvPoke";
				}
			}

			function addHintMoveDetails(pokemon, isYours){
				// Display move data
				fastMove = pokemon.fastMove

				if(isYours){
					var $details = $(".yours .quiz-omt-hints-container");
				} else {
					var $details = $(".opponents .quiz-omt-hints-container");
				}
				// Clear previous content
				$details.empty();
				// Append details template
				$details.append($(".details-template.hide").html());

				var $moveDetails = $details.find(".moveset.fast .move-detail-template.hide").clone();
				$moveDetails.removeClass("hide");

				// Contextualize the move archetype for this Pokemon
				var archetype = fastMove.archetype;
				var archetypeClass = 'general'; // For CSS

				if(fastMove.archetype == "Fast Charge"){
					archetypeClass = "spam";
				} else if(fastMove.archetype == "Heavy Damage"){
					archetypeClass = "nuke";
				} else if(fastMove.archetype == "Multipurpose"){
					archetypeClass = "high-energy";
				} else if(fastMove.archetype == "Low Quality"){
					archetypeClass = "low-quality";
				}

				$moveDetails.addClass(fastMove.type);
				$moveDetails.find(".name").html(fastMove.displayName);
				$moveDetails.find(".archetype .name").html(archetype);
				$moveDetails.find(".archetype .icon").addClass(archetypeClass);
				$moveDetails.find(".dpt .value").html(Math.round( ((fastMove.power * fastMove.stab * pokemon.shadowAtkMult) / (fastMove.cooldown / 500)) * 100) / 100);
				$moveDetails.find(".ept .value").html(Math.round( (fastMove.energyGain / (fastMove.cooldown / 500)) * 100) / 100);
				$moveDetails.find(".turns .value").html( fastMove.cooldown / 500 );
				$moveDetails.attr("data", fastMove.moveId);

				// Highlight this move if it's in the recommended moveset

				if(fastMove == pokemon.fastMove){
					$moveDetails.addClass("selected");
				}

				$details.find(".moveset.fast").append($moveDetails);
			}

			// Set a context so this interface can add or skip functionality

			this.setContext = function(value){
				context = value;

				if(context == "custom"){
					$(".league-select option[value='500']").show();
				}
			}

			// Set a ranking scenario to be displayed

			this.setScenario = function(value){
				scenario = value;
			}

			// Link the custom ranking interface so these two can talk

			this.setCustomRankingInterface = function(obj){
				customRankingInterface = obj;
			}

			// Return a custom group of the top 100 Pokemon

			this.getMetaGroup = function(){
				return metaGroup;
			}

			// Event handler for changing the league select

			function selectLeague(e){
				var cp = battle.getCP();
				var levelCap = parseInt($(".league-select option:selected").attr("level-cap"));

				if(context != "custom"){
					var category = $(".category-select option:selected").val();
					var cup = battle.getCup().name;

					if(cp == 500){
						$(".format-select option[cup=\"little\"]").prop("selected","selected");
						cup = "little";
					} else if(cup == "little"){
						$(".format-select option[cup=\"all\"]").prop("selected","selected");
						cup = "all";
					}

					battle.setCup(cup);

					self.displayRankings(category, cp, cup);
					self.pushHistoryState(cup, cp, category, null);
				} else{
					cp = $(".league-select option:selected").val();
				}

				battle.setCP(cp);
				battle.setLevelCap(levelCap);
			}

			// Event handler for changing the cup select

			function selectFormat(e){
				var cp = $(".format-select option:selected").val();
				var cup = $(".format-select option:selected").attr("cup");
				var category = $(".category-select option:selected").val();
				var sort = $(".category-select option:selected").attr("sort");

				if(! category){
					category = "overall";
				}

				if(cup == "custom"){
					window.location.href = webRoot+'custom-rankings/';
					return;
				}

				self.displayRankings(category, cp, cup);
				self.pushHistoryState(cup, cp, category, null);
			}

			function nextQuestion(){
				$(".quiz-feedback-header").addClass("hidden")
				$(".quiz-feedback").addClass("hidden")
				$(".quiz-feedback-explanation").addClass("hidden")
				$(".quiz-feedback-explanation").addClass("hidden")
				$("details").removeAttr("open");
				self.displayRankingData(self.rankings)
			}

			function checkAnswer() {
				var quizAnswerInputValue = $(".quiz-answer-input option:selected").val();
				console.log(quizAnswerInputValue)
				result = false
				trials++
				if((optimalTimes.length == 0 && quizAnswerInputValue == 'No optimal timing possible') || 
					optimalTimes.join(",") == quizAnswerInputValue){
					result = true
				}
				if(result && trials == 1){
					numberCorrectAnswers++
				}
				
				// Show feedback
				$(".quiz-feedback-header").removeClass("hidden");
				if(!result){
					$(".quiz-feedback")
						.removeClass("hidden feedback-correct")
						.addClass("feedback-wrong")
						.text("❌ " + quizAnswerInputValue + " is not the correct answer, try again!");
				} else {
					$(".quiz-feedback")
						.removeClass("hidden feedback-wrong")
						.addClass("feedback-correct")
						.text("✅ " + quizAnswerInputValue + " is the correct answer!");
					$(".quiz-feedback-explanation").removeClass("hidden");
				}

				updateScore()
				updateAnswersHistory(self.yourPokemon, self.opponentsPokemon, result)
			}

			function updateAnswersHistory(yourPokemon, opponentsPokemon, result){
				// Only at correct answers at first trial are considered corrected
				if(trials > 1){
					result = false
				}
				questionKey = pokemon.speciesId + '|' + fastMove.moveId + '|' + chargedMove.moveId
				self.questionAnswers[questionKey] = result
			}

			function updateScore(){
				// Select the quiz-score container
				var $score = $(".quiz-score");

				// Update the current score
				$score.children().eq(1).text(numberCorrectAnswers);
				$score.children().eq(3).text(numberAskedQuestions);
			}

			// Event handler for selecting ranking category

			function selectCategory(e){

				var cp = $(".format-select option:selected").val();
				var category = $(".category-select option:selected").val();
				var sort = $(".category-select option:selected").attr("sort");
				var scenarioStr = $(".category-select option:selected").attr("scenario");
				var cup = $(".format-select option:selected").attr("cup");

				$(".description").hide();
				if(sort == "score"){
					$(".description."+category).show();
				} else{
					$(".description."+sort).show();
				}

				// Set the corresponding scenario

				for(var i = 0; i < scenarios.length; i++){
					if(scenarios[i].slug == scenarioStr){
						scenario = scenarios[i];
						break;
					}
				}

				self.displayRankings(category, cp, cup);

				self.pushHistoryState(cup, cp, category, null);
			}

			// Turn checkboxes on and off

			function checkBox(e){
				$(this).toggleClass("on");
				$(this).trigger("stateChange");
			}

		};
        return object;
    }

    return {
        getInstance: function () {
            if (!instance) {
                instance = createInstance();
            }
            return instance;
        }
    };
})();
