<?php
// This file is generated by compile.php. Do not edit directly.
$formats = array (
  0 => 
  array (
    'title' => 'P!P Championship Series',
    'cup' => 'championshipseries',
    'cp' => 1500,
    'meta' => 'championshipseries',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'hideRankings' => true,
  ),
  1 => 
  array (
    'title' => 'Scroll Cup',
    'cup' => 'scroll',
    'cp' => 1500,
    'meta' => 'scroll',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 1,500 CP to enter.',
      1 => 'Only Water-, Fighting-, and Dark-type Pokémon are eligible.',
      2 => 'The following Pokémon will not be allowed: Primarina',
    ),
  ),
  2 => 
  array (
    'title' => 'Holiday Cup (Great League)',
    'cup' => 'holiday',
    'cp' => 1500,
    'meta' => 'holiday',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 1,500 CP to enter.',
      1 => 'Only Normal-, Grass-, Electric-, Ice-, Flying-, and Ghost-type Pokémon are eligible.',
    ),
  ),
  3 => 
  array (
    'title' => 'Holiday Cup (Ultra League)',
    'cup' => 'holiday',
    'cp' => 2500,
    'meta' => 'holidayultra',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 2,500 CP to enter.',
      1 => 'Only Normal-, Grass-, Electric-, Ice-, Flying-, and Ghost-type Pokémon are eligible.',
    ),
  ),
  4 => 
  array (
    'title' => 'EUIC 2026 Championship Series Cup',
    'cup' => 'euic2026',
    'cp' => 1500,
    'meta' => 'euic2026',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  5 => 
  array (
    'title' => 'Battle Frontier (Calamity)',
    'cup' => 'calamity',
    'cp' => 1500,
    'meta' => 'calamity',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  6 => 
  array (
    'title' => 'Battle Frontier (Ultra)',
    'cup' => 'battlefrontierultra',
    'cp' => 2500,
    'meta' => 'ultra',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  7 => 
  array (
    'title' => 'Battle Frontier (Master)',
    'cup' => 'battlefrontiermaster',
    'cp' => 10000,
    'meta' => 'battlefrontiermaster',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  8 => 
  array (
    'title' => 'Devon Nettle Cup',
    'cup' => 'nettle',
    'cp' => 1500,
    'meta' => 'nettle',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  9 => 
  array (
    'title' => 'Gymbreakers LAIC 2025 Remix',
    'cup' => 'laic2025remix',
    'cp' => 1500,
    'meta' => 'laic2025remix',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  10 => 
  array (
    'title' => 'Zygarden Chrono Meta',
    'cup' => 'chrono',
    'cp' => 1500,
    'meta' => 'chrono',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  11 => 
  array (
    'title' => 'Little Cup',
    'cup' => 'little',
    'cp' => 500,
    'meta' => 'little',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
  ),
  12 => 
  array (
    'title' => 'Catch Cup',
    'cup' => 'catch',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
  ),
  13 => 
  array (
    'title' => 'Custom',
    'cup' => 'custom',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => false,
  ),
);
?>