<?php
// This file is generated by compile.php. Do not edit directly.
$formats = array (
  0 => 
  array (
    'title' => 'P!P Championship Series',
    'cup' => 'championshipseries',
    'cp' => 1500,
    'meta' => 'championshipseries',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'hideRankings' => true,
  ),
  1 => 
  array (
    'title' => 'Jungle Cup',
    'cup' => 'jungle',
    'cp' => 1500,
    'meta' => 'jungle',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 1,500 CP to enter.',
      1 => 'Only Normal-, Grass-, Electric-, Poison-, Ground-, Flying-, Bug-, and Dark-type Pokémon are eligible.',
      2 => 'The following Pokémon will not be allowed: Gligar, Galarian Stunfisk',
    ),
  ),
  2 => 
  array (
    'title' => 'Master Premier',
    'cup' => 'premier',
    'cp' => 10000,
    'meta' => 'premiermaster',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'No CP limit.',
      1 => 'Legendary Pokémon, Mythical Pokémon, and Ultra Beasts are not eligible.',
    ),
  ),
  3 => 
  array (
    'title' => 'Great League Remix',
    'cup' => 'remix',
    'cp' => 1500,
    'meta' => 'remix',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 1,500 CP to enter.',
      1 => 'The following Pokémon will not be allowed: Blastoise, Primeape, Marowak, Azumarill, Dunsparce, Scizor, Galarian Corsola, Altaria, Cradily, Dusclops, Empoleon, Bastiodon, Gastrodon, Togekiss, Stunfisk, Talonflame, Dedenne, Corviknight, Annihilape',
    ),
  ),
  4 => 
  array (
    'title' => 'Halloween Cup',
    'cup' => 'halloween',
    'cp' => 1500,
    'meta' => 'halloween',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 1,500 CP to enter.',
      1 => 'Only Poison-, Bug-, Ghost-, Dark-, and Fairy-type Pokémon are eligible.',
    ),
  ),
  5 => 
  array (
    'title' => 'Mega Master League',
    'cup' => 'mega',
    'cp' => 10000,
    'meta' => 'mega',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
    'hideRankings' => true,
    'rules' => 
    array (
      0 => 'No CP limit.',
      1 => 'Mega-Evolved Pokémon are allowed.',
    ),
  ),
  6 => 
  array (
    'title' => 'LAIC 2025 Championship Series Cup',
    'cup' => 'laic2025',
    'cp' => 1500,
    'meta' => 'laic2025',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  7 => 
  array (
    'title' => 'Battle Frontier (Calamity)',
    'cup' => 'calamity',
    'cp' => 1500,
    'meta' => 'calamity',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  8 => 
  array (
    'title' => 'Battle Frontier (Ultra)',
    'cup' => 'battlefrontierultra',
    'cp' => 2500,
    'meta' => 'ultra',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  9 => 
  array (
    'title' => 'Battle Frontier (Master)',
    'cup' => 'battlefrontiermaster',
    'cp' => 10000,
    'meta' => 'battlefrontiermaster',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  10 => 
  array (
    'title' => 'Devon Metamorphosis Cup',
    'cup' => 'metamorphosis',
    'cp' => 1500,
    'meta' => 'metamorphosis',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  11 => 
  array (
    'title' => 'Gymbreakers Pillar Cup Remix',
    'cup' => 'pillar3',
    'cp' => 1500,
    'meta' => 'pillar3',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  12 => 
  array (
    'title' => 'Zygarden Chrono Meta',
    'cup' => 'chrono',
    'cp' => 1500,
    'meta' => 'chrono',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  13 => 
  array (
    'title' => 'Little Cup',
    'cup' => 'little',
    'cp' => 500,
    'meta' => 'little',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
  ),
  14 => 
  array (
    'title' => 'Catch Cup',
    'cup' => 'catch',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
  ),
  15 => 
  array (
    'title' => 'Custom',
    'cup' => 'custom',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => false,
  ),
);
?>